# Generated by Django 6.0.2 on 2026-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número de telefone/WhatsApp', max_length=20, null=True),
        ),
    ]
