# Generated by Django 6.0.2 on 2026-02-07 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_empresa_last_checked_empresa_status_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(help_text='ID externo da nota', max_length=128)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ISSUED', 'ISSUED'), ('CANCELLED', 'CANCELLED'), ('DRAFT', 'DRAFT')], default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='monitor.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'invoice_id')},
            },
        ),
    ]
