# Generated by Django 6.0.2 on 2026-02-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alert_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mei_login',
            field=models.CharField(blank=True, help_text='Login/CPF do MEI para integração', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mei_password',
            field=models.CharField(blank=True, help_text='Senha (guarde com segurança)', max_length=255, null=True),
        ),
    ]
