# Generated by Django 6.0.2 on 2026-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_empresa_mei_login_empresa_mei_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_remote',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
