# Generated by Django 6.0.2 on 2026-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_invoice_is_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(help_text='ID externo da nota', max_length=128, verbose_name='Preencha o numero da nota'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Emitida'), ('CANCELLED', 'Cancelada'), ('DRAFT', 'Rascunho')], default='Emitida', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Faturado'),
        ),
    ]
