# Generated by Django 6.0.2 on 2026-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_invoice_invoice_id_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Aviso'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10),
        ),
    ]
