# Generated by assistant to change default status and update existing records
from django.db import migrations, models


def set_status_ativo(apps, schema_editor):
    Empresa = apps.get_model('monitor', 'Empresa')
    Empresa.objects.filter(status='unknown').update(status='ATIVO')


def revert_status_unknown(apps, schema_editor):
    Empresa = apps.get_model('monitor', 'Empresa')
    Empresa.objects.filter(status='ATIVO').update(status='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(max_length=50, default='ATIVO'),
        ),
        migrations.RunPython(set_status_ativo, revert_status_unknown),
    ]

