# Generated by Django 6.0.2 on 2026-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_update_empresa_status_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(help_text='Preencha o numero ou dê um nome à nota para identificação', max_length=128, verbose_name='Preencha o numero da nota'),
        ),
    ]
