# Generated by Django 6.0.2 on 2026-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Aviso'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='notified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(db_index=True, help_text='Preencha o numero ou dê um nome à nota para identificação', max_length=128, verbose_name='Preencha o numero da nota'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Emitida'), ('CANCELLED', 'Cancelada'), ('DRAFT', 'Rascunho')], db_index=True, default='ISSUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['empresa', '-created_at'], name='monitor_ale_empresa_bab544_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['empresa', 'notified', '-created_at'], name='monitor_ale_empresa_c8a02a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='monitor_inv_status_ab5b37_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-created_at'], name='monitor_inv_status_369dc9_idx'),
        ),
    ]
