# Generated by Django 6.0.2 on 2026-04-11 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0011_add_indexes_for_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(help_text='Nome profissional/studio', max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('FREE', 'Plano Gratuito'), ('PREMIUM', 'Plano Premium'), ('ENTERPRISE', 'Plano Enterprise')], default='FREE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Contador',
                'verbose_name_plural': 'Perfis de Contadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa mensal cobrada', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o cliente')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accountants.accountantprofile')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_clients', to='monitor.empresa')),
            ],
            options={
                'verbose_name': 'Cliente de Contador',
                'verbose_name_plural': 'Clientes de Contadores',
                'ordering': ['-created_at'],
                'unique_together': {('accountant', 'empresa')},
            },
        ),
    ]
