# Generated by Django 6.0.2 on 2026-02-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='bot_token',
            field=models.CharField(blank=True, help_text='Token do bot (opcional). Se vazio, será usado o token global nas settings.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Indica se as notificações do Telegram estão ativadas para este usuário.', verbose_name='Ativo'),
        ),
    ]
