# Generated by Django 6.0.2 on 2026-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramprofile_bot_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='bot_token',
            field=models.CharField(blank=True, help_text='Cole aqui o token que obteve no seu telegram.', max_length=256, null=True),
        ),
    ]
