# Generated by Django 6.0.2 on 2026-04-09 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', max_length=10)),
                ('action_type', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('CANCEL', 'Cancelamento'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ERROR', 'Erro'), ('ALERT', 'Alerta'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação'), ('OTHER', 'Outro')], db_index=True, default='OTHER', max_length=20)),
                ('title', models.CharField(help_text='Título ou descrição curta da ação', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do que aconteceu')),
                ('module', models.CharField(db_index=True, help_text='Módulo ou app que gerou o log (ex: invoice, empresa, etc)', max_length=100)),
                ('action_object_id', models.IntegerField(blank=True, db_index=True, help_text='ID do objeto que foi modificado', null=True)),
                ('action_object_type', models.CharField(blank=True, help_text='Tipo de objeto (ex: Invoice, Empresa, etc)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent do navegador')),
                ('old_values', models.JSONField(blank=True, help_text='Valores antigos (para auditorias)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Novos valores (para auditorias)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='logs_system_created_491ae5_idx'), models.Index(fields=['user', '-created_at'], name='logs_system_user_id_21ef4d_idx'), models.Index(fields=['level', '-created_at'], name='logs_system_level_c7c9de_idx'), models.Index(fields=['action_type', '-created_at'], name='logs_system_action__ae2a2f_idx'), models.Index(fields=['module', '-created_at'], name='logs_system_module_82d0e5_idx')],
            },
        ),
    ]
